#!/bin/bash
log_file=/var/tmp/oraprdcgy107b-login-check/logs/log_`date +%Y%m%d%H%M%S`.log
check_login()
{
ssh oraprdcgy107b 'uptime' >/dev/null 2>/dev/null
if [ $? -eq 0 ]
then
        echo "Login successful at : `date`" | tee -a $log_file
        sleep 60
        check_login
else
